/* data-auteurs.js — Principaux auteurs (source : docs/Principaux auteurs.docx + développements bac) */
const AUTEURS_GENRES = [
  { id: '', label: 'Tous' },
  { id: 'poesie', label: 'Poésie', test: g => /poésie/i.test(g) && !/roman/i.test(g) },
  { id: 'roman', label: 'Roman', test: g => (/roman|contes/i.test(g) && !/poésie/i.test(g)) || g === 'Contes — formes dramatiques' },
  { id: 'theatre', label: 'Théâtre', test: g => /théâtre|theatre|dramatique/i.test(g) },
  { id: 'idees', label: "Litt. d'idées", test: g => /idées/i.test(g) },
  { id: 'mixte', label: 'Poésie & roman', test: g => g === 'Poésie / Roman' || g === 'Roman et Poésie' },
];

const AUTEURS_DATA = [
  {
    id: 'rimbaud', nom: 'Arthur Rimbaud', genre: 'Poésie', dates: '1854 – 1891',
    mouvement: 'Poésie moderne — poète « voyant » et maudit',
    oeuvres: 'Une Saison en enfer (1873) · Le Bateau ivre (1871) · Illuminations (1886)',
    intro: ['Époque : fin XIXe — symbolisme, poète « maudit ».', 'Fonction : poète ; cherche une « alchimie du verbe ».', 'Œuvre à citer : Le Bateau ivre (1871) ou Une Saison en enfer (1873).', 'Amorce : du Parnasse à la rupture symboliste et à la poésie visionnaire.', 'Phrase type : « Arthur Rimbaud (1854-1891), poète français, écrit Le Bateau ivre en 1871, texte fondateur de la modernité poétique. »'],
    dev: 'Poète précoce et révolté, Rimbaud cherche une « alchimie du verbe » : le poème doit transformer la réalité, pas la décrire. Le Bateau ivre illustre l\'ivresse créatrice puis l\'épuisement du « je » poétique. Une Saison en enfer mêle prose lyrique, auto-analyse et registre satirique. Au bac : repère l\'audace des images, la musicalité et la rupture avec la poésie descriptive.',
  },
  {
    id: 'baudelaire', nom: 'Charles Baudelaire', genre: 'Poésie', dates: '1821 – 1867',
    mouvement: 'Modernité poétique — spleen, correspondances, ville moderne',
    oeuvres: 'Les Fleurs du mal (1857) · Le Spleen de Paris (petits poèmes en prose)',
    intro: ['Époque : milieu XIXe — poésie moderne, symbolisme.', 'Fonction : poète, critique d\'art ; thèmes : spleen, idéal, ville.', 'Œuvre à citer : Les Fleurs du mal (1857).', 'Amorce : du romantisme à la poésie de la modernité et de la laideur.', 'Phrase type : « Charles Baudelaire (1821-1867), poète majeur, publie en 1857 Les Fleurs du mal. »'],
    dev: 'Baudelaire invente une poésie de la modernité : la ville, la foule, la laideur deviennent sources d\'esthétique (« correspondances » entre sens). Les Fleurs du mal explore le mal, le temps qui passe et la quête d\'idéal dans un registre lyrique et parfois satirique. Au bac : cite les procédés qui traduisent mélancolie, étrangeté ou tension entre spleen et idéal.',
  },
  {
    id: 'verlaine', nom: 'Paul Verlaine', genre: 'Poésie', dates: '1844 – 1896',
    mouvement: 'Symbolisme — poésie de l\'impression et de la musicalité (à partir des années 1880)',
    oeuvres: 'Poèmes saturniens · Romances sans paroles · Les Poètes maudits (1884, 1888)',
    note: 'Lié à Rimbaud ; figure des « poètes maudits ».',
    intro: ['Époque : fin XIXe — symbolisme, musicalité du vers.', 'Fonction : poète ; « de la musique avant toute chose ».', 'Œuvre à citer : Poèmes saturniens ou Chanson d\'automne (1866).', 'Amorce : poésie de l\'impression et du « vers et allers ».', 'Phrase type : « Paul Verlaine (1844-1896), poète symboliste, publie Poèmes saturniens et cultive la musicalité du vers. »'],
    dev: 'Verlaine privilégie la nuance, la musicalité et l\'impression plutôt que la description précise (« de la musique avant toute chose »). Chanson d\'automne (assonances, registre mélancolique) est un classique du bac. Au bac : relie sons répétés, rythme du vers libre ou régulier et tonalité lyrique ou nostalgique.',
  },
  {
    id: 'ponge', nom: 'Francis Ponge', genre: 'Poésie', dates: '1899 – 1988',
    mouvement: 'Surréalisme puis « prose du monde » — élévation du banal',
    oeuvres: "Le Parti pris des choses (1942) · La Rage de l'expression (1952) · Le Savon",
    intro: ['Époque : XXe — après surréalisme, « prose du monde ».', 'Fonction : poète-prosaïste ; thème : l\'objet ordinaire.', 'Œuvre à citer : Le Parti pris des choses (1942).', 'Amorce : renouvellement de la poésie par le banal et la précision lexicale.', 'Phrase type : « Francis Ponge (1899-1988), poète français, publie en 1942 Le Parti pris des choses. »'],
    dev: 'Ponge écrit sur des objets ordinaires (pain, savon, huître) pour en révéler la « chose » en soi, loin du lyrisme romantique. Sa prose poétique mêle humour, précision lexicale et réflexion sur le langage. Au bac : montre comment le style (champ lexical, comparaisons, énumérations) transforme le banal en méditation.',
  },
  {
    id: 'mallarme', nom: 'Stéphane Mallarmé', genre: 'Poésie', dates: '1842 – 1898',
    mouvement: 'Symbolisme — poésie pure, suggestion et blanc du verbe',
    oeuvres: 'Poésies · Un coup de dés jamais n\'abolira le hasard (1897)',
    intro: ['Époque : fin XIXe — symbolisme, poésie pure.', 'Fonction : poète ; maître de la suggestion et du hasard.', 'Œuvre à citer : Un coup de dés… (1897) ou Poésies.', 'Amorce : poésie qui suggère plutôt qu\'elle ne nomme.', 'Phrase type : « Stéphane Mallarmé (1842-1898), poète symboliste, mène la poésie vers la suggestion et la modernité du vers. »'],
    dev: 'Mallarmé pousse le symbolisme vers la « poésie pure » : le poème suggère plutôt qu\'il ne nomme, le hasard et la page deviennent matière poétique. Son influence sur le XXe siècle est majeure (modernité du vers et de la mise en page). Au bac : insiste sur la densité du sens, les symboles et l\'effet d\'énigme ou de suspension.',
  },
  {
    id: 'dorion', nom: 'Hélène Dorion', genre: 'Poésie / Roman', dates: '1958 –',
    mouvement: 'Contemporain — poésie québécoise, mémoire et nature',
    oeuvres: 'Mes forêts (2021) · Ravir : poème du monde (1997)',
    note: 'Née au Québec.',
    intro: ['Époque : contemporaine — littérature québécoise.', 'Fonction : poète et romancière ; thèmes : nature, mémoire.', 'Œuvre à citer : Mes forêts (2021).', 'Amorce : voix féminine contemporaine, écologie et intériorité.', 'Phrase type : « Hélène Dorion (1958-), poète québécoise, publie Mes forêts en 2021. »'],
    dev: 'Poète et romancière québécoise contemporaine : la nature, la mémoire et la fragilité du monde habitent son écriture. Mes forêts illustre une poésie attentive au vivant et au paysage intérieur. Au bac : repère registre lyrique ou méditatif, images de la nature et rapport du « je » au temps.',
  },
  {
    id: 'jacob', nom: 'Max Jacob', genre: 'Poésie / Roman', dates: '1876 – 1944',
    mouvement: 'Cubisme — précurseur du dadaïsme et du surréalisme',
    oeuvres: 'Le Cornet à dés · Histoire du roi Kaboul Ier et du marmiton Gauwain',
    intro: ['Époque : début XXe — cubisme, avant-garde parisienne.', 'Fonction : poète et prosaïste ; humour, mystique, fantaisie.', 'Œuvre à citer : Le Cornet à dés.', 'Amorce : rupture avec le récit réaliste, proximité de Picasso.', 'Phrase type : « Max Jacob (1876-1944), poète et écrivain, proche du cubisme et de l\'avant-garde. »'],
    dev: 'Proche de Picasso et Apollinaire, Jacob mêle fantaisie, humour et mystique dans une prose poétique fragmentée. Le Cornet à dés annonce les jeux de forme du XXe siècle. Au bac : valorise l\'originalité du ton (comique, absurde, lyrique) et la rupture avec le récit linéaire.',
  },
  {
    id: 'balzac', nom: 'Honoré de Balzac', genre: 'Roman', dates: '1799 – 1850',
    mouvement: 'Réalisme — peinture de la société post-révolutionnaire',
    oeuvres: 'La Comédie humaine (1830–1856) · Le Père Goriot (1835) · La Peau de chagrin (1831)',
    intro: ['Époque : première moitié XIXe — réalisme, monarchie de Juillet.', 'Fonction : romancier ; panorama social de la France.', 'Œuvre à citer : Le Père Goriot (1835) ou La Comédie humaine.', 'Amorce : du romantisme au roman « miroir » de la société.', 'Phrase type : « Honoré de Balzac (1799-1850), romancier majeur, publie Le Père Goriot en 1835 dans La Comédie humaine. »'],
    dev: 'Balzac dresse un panorama de la France du XIXe siècle : classes sociales, argent, ambition, déclin. La Comédie humaine relie des romans par des personnages-recurrents. Au bac : analyse personnages types, champs lexicaux sociaux, narrateur omniscient et critique de la société.',
  },
  {
    id: 'zola', nom: 'Émile Zola', genre: 'Roman', dates: '1840 – 1902',
    mouvement: 'Naturalisme — roman expérimental, hérédité et milieu',
    oeuvres: "Germinal (1885) · J'accuse (1898) · La Bête humaine (1890) · Les Rougon-Macquart",
    intro: ['Époque : second XIXe — naturalisme, IIIe République.', 'Fonction : romancier et polémiste ; thème : milieu, hérédité, misère.', 'Œuvre à citer : Germinal (1885) ou J\'accuse (1898).', 'Amorce : romantisme → réalisme/naturalisme influencé par les sciences.', 'Phrase type : « Émile Zola (1840-1902), romancier naturaliste, publie Germinal en 1885. »'],
    dev: 'Zola applique une méthode « scientifique » au roman : le milieu, l\'hérédité et les instincts déterminent les personnages. Germinal dénonce la misère ouvrière ; J\'accuse est un texte d\'idées engagé (affaire Dreyfus). Au bac : repère vocabulaire du corps, du travail, champs lexicaux de la violence ou de la révolte.',
  },
  {
    id: 'stendhal', nom: 'Stendhal', genre: 'Roman', dates: '1783 – 1842',
    mouvement: 'Réalisme — psychologie, ironie et « cristal et prisme »',
    oeuvres: 'Le Rouge et le Noir (1830) · La Chartreuse de Parme (1839)',
    intro: ['Époque : début XIXe — Restauration, monarchie de Juillet.', 'Fonction : romancier ; analyse psychologique et sociale.', 'Œuvre à citer : Le Rouge et le Noir (1830).', 'Amorce : roman de l\'ambition et de la hypocrisie sociale.', 'Phrase type : « Stendhal (1783-1842), romancier, publie Le Rouge et le Noir en 1830. »'],
    dev: 'Stendhal analyse les passions et les calculs sociaux (Julien Sorel, ambition et hypocrisie). Son style privilégie la concision, l\'ironie et la lucidité psychologique. Au bac : montre focalisation, registres (pathétique, satirique) et critique des conventions sociales.',
  },
  {
    id: 'maupassant', nom: 'Guy de Maupassant', genre: 'Roman', dates: '1850 – 1893',
    mouvement: 'Réalisme — nouvelle et roman, effet de réel',
    oeuvres: 'Bel-Ami (1885) · La Parure · Le Horla · Pierre et Jean',
    intro: ['Époque : fin XIXe — réalisme, maître de la nouvelle.', 'Fonction : romancier et nouvelliste ; élève de Flaubert.', 'Œuvre à citer : Bel-Ami (1885) ou La Parure (1884).', 'Amorce : effet de réel, chute de la nouvelle, fantastique (Le Horla).', 'Phrase type : « Guy de Maupassant (1850-1893), nouvelliste et romancier, publie Bel-Ami en 1885. »'],
    dev: 'Élève de Flaubert, Maupassant excelle dans la nouvelle : chute finale, sobriété narrative, peinture de la Normandie et de la bourgeoisie. Le Horla explore la folie et l\'invisible. Au bac : repère chute du conte, ellipse narrative, registre fantastique ou réaliste.',
  },
  {
    id: 'flaubert', nom: 'Gustave Flaubert', genre: 'Roman', dates: '1821 – 1880',
    mouvement: 'Réalisme — « impersonalité » de l\'auteur, travail du style',
    oeuvres: 'Madame Bovary (1857) · L\'Éducation sentimentale (1869) · Trois Contes',
    intro: ['Époque : milieu XIXe — réalisme, recherche du mot juste.', 'Fonction : romancier ; thème : bovarysme, rêve et réalité.', 'Œuvre à citer : Madame Bovary (1857).', 'Amorce : roman réaliste et critique des illusions romantiques.', 'Phrase type : « Gustave Flaubert (1821-1880), romancier, publie Madame Bovary en 1857. »'],
    dev: 'Flaubert recherche la précision du mot juste et l\'objectivité narrative : le bovarysme (rêve vs réalité) structure Madame Bovary. Son style mélange ironie, description réaliste et subjectivité contenue. Au bac : analyse champs lexicaux, free indirect style et distance du narrateur.',
  },
  {
    id: 'hugo', nom: 'Victor Hugo', genre: 'Roman', dates: '1802 – 1885',
    mouvement: 'Romantisme — engagement, lyrisme et « grotesque »',
    oeuvres: 'Notre-Dame de Paris (1831) · Les Misérables (1862) · Les Contemplations',
    intro: ['Époque : XIXe — romantisme, engagement politique.', 'Fonction : poète, romancier, dramaturge ; défense du peuple.', 'Œuvre à citer : Les Misérables (1862) ou Notre-Dame de Paris (1831).', 'Amorce : Lumières → romantisme (subjectivité, nature, « mal du siècle »).', 'Phrase type : « Victor Hugo (1802-1885), écrivain romantique, publie Les Misérables en 1862. »'],
    dev: 'Hugo unit poésie, roman et engagement politique : le peuple, la justice et la misère sont au cœur de Les Misérables. Le romantisme hugolien mêle pathos, digressions et symboles (lumière / ténèbres). Au bac : repère antithèses, anaphores, registres pathétique ou épique.',
  },
  {
    id: 'sainte-beuve', nom: 'Charles-Augustin Sainte-Beuve', genre: 'Roman', dates: '1804 – 1869',
    mouvement: 'Romantisme — critique littéraire et portraits',
    oeuvres: 'Port-Royal · Causeries du lundi · Volupté (roman)',
    intro: ['Époque : XIXe — romantisme, naissance de la critique moderne.', 'Fonction : critique et romancier ; « botanique littéraire ».', 'Œuvre à citer : Causeries du lundi ou Volupté.', 'Amorce : place de l\'auteur dans son époque (utile en intro).', 'Phrase type : « Charles-Augustin Sainte-Beuve (1804-1869), critique et écrivain du romantisme. »'],
    dev: 'Sainte-Beuve invente la critique littéraire moderne : il replace l\'œuvre dans la biographie et le milieu (« botanique littéraire »). Volupté est un roman romantique introspectif. Au bac : utile pour contextualiser un auteur ou une époque dans une introduction ou une dissertation.',
  },
  {
    id: 'lamartine', nom: 'Alphonse de Lamartine', genre: 'Roman et Poésie', dates: '1790 – 1869',
    mouvement: 'Romantisme — méditations, nature et temps qui passe',
    oeuvres: 'Méditations poétiques (1820) · Le Lac · Graziella · Histoire des Girondins',
    intro: ['Époque : début XIXe — romantisme lyrique naissant.', 'Fonction : poète et homme politique ; thème : temps, nature, souvenir.', 'Œuvre à citer : Méditations poétiques (1820) ou Le Lac.', 'Amorce : ouverture du romantisme français (1820).', 'Phrase type : « Alphonse de Lamartine (1790-1869), poète romantique, publie Méditations poétiques en 1820. »'],
    dev: 'Lamartine ouvre le romantisme lyrique français : nature, souvenir amoureux et mélancolie du temps (Le Lac). Homme politique, il écrit aussi des récits et de l\'histoire. Au bac : analyse registre lyrique, personnification de la nature et thème du temps irréversible.',
  },
  {
    id: 'nodier', nom: 'Charles Nodier', genre: 'Roman', dates: '1780 – 1844',
    mouvement: 'Romantisme — conte fantastique et salon littéraire',
    oeuvres: 'Adèle (1820) · Smarra · Trilby · La Fée aux miettes',
    intro: ['Époque : début XIXe — romantisme, conte fantastique.', 'Fonction : écrivain, animateur du salon de l\'Arsenal.', 'Œuvre à citer : Smarra ou La Fée aux miettes.', 'Amorce : renouveau du fantastique romantique.', 'Phrase type : « Charles Nodier (1780-1844), écrivain romantique, cultive le conte fantastique. »'],
    dev: 'Nodier anime le romantisme parisien (Arsenal) et cultive le conte fantastique et onirique. Ses récits mêlent rêve, mort et séduction. Au bac : repère registre fantastique, narrateur et atmosphère onirique dans les nouvelles romantiques.',
  },
  {
    id: 'daudet', nom: 'Alphonse Daudet', genre: 'Contes — formes dramatiques', dates: '1840 – 1897',
    mouvement: 'Réalisme — Provence, mémoire et ton narratif',
    oeuvres: 'Tartarin de Tarascon (1872) · Les Lettres de mon moulin (1896) · Le Petit Chose',
    intro: ['Époque : second XIXe — réalisme, conte provençal.', 'Fonction : romancier et conteur ; ton comique et nostalgique.', 'Œuvre à citer : Les Lettres de mon moulin (1896) ou Tartarin (1872).', 'Amorce : mémoire d\'enfance et oralité du récit.', 'Phrase type : « Alphonse Daudet (1840-1897), écrivain, publie Les Lettres de mon moulin en 1896. »'],
    dev: 'Daudet mêle humour, tendresse et nostalgie (Provence, enfance). Les Lettres de mon moulin et Tartarin illustrent le conte réaliste avec verve comique. Au bac : repère registre comique ou pathétique, oralité du récit et champs lexicaux régionaux.',
  },
  {
    id: 'colette', nom: 'Colette', genre: 'Roman', dates: '1873 – 1954',
    mouvement: 'Réalisme — sensualité, nature et liberté féminine',
    oeuvres: "Claudine à l'école (1900) · Sido · Chéri · La Chatte",
    intro: ['Époque : fin XIXe – XXe — voix féminine, sensualité.', 'Fonction : romancière ; thèmes : nature, corps, liberté.', 'Œuvre à citer : Claudine à l\'école (1900) ou Sido.', 'Amorce : écriture sensorielle et autobiographie fictive.', 'Phrase type : « Colette (1873-1954), romancière, publie Claudine à l\'école en 1900. »'],
    dev: 'Colette décrit la sensualité, la nature et l\'émancipation féminine avec un style sensoriel et précis. Claudine lance une saga autobiographique fictive ; Sido célèbre la mère et le pays breton. Au bac : analyse champs lexicaux sensoriels, focalisation et registre lyrique ou réaliste.',
  },
  {
    id: 'gide', nom: 'André Gide', genre: 'Roman', dates: '1869 – 1951',
    mouvement: 'Modernité — quête morale, journal et métafiction',
    oeuvres: 'Les Faux-Monnayeurs (1925) · L\'Immoraliste · Les Nourritures terrestres · La Porte étroite',
    intro: ['Époque : fin XIXe – XXe — modernité, Nobel 1947.', 'Fonction : romancier ; thème : liberté, morale, écriture.', 'Œuvre à citer : Les Faux-Monnayeurs (1925).', 'Amorce : questionnement moral et mise en abyme romanesque.', 'Phrase type : « André Gide (1869-1951), romancier, publie Les Faux-Monnayeurs en 1925. »'],
    dev: 'Gide explore la liberté individuelle, la morale et la création (mise en abyme dans Les Faux-Monnayeurs). Prix Nobel 1947. Au bac : repère registre autobiographique, questionnement moral et jeux sur l\'écriture.',
  },
  {
    id: 'rolland', nom: 'Romain Rolland', genre: 'Roman', dates: '1866 – 1944',
    mouvement: 'Pacifisme — humanisme, Prix Nobel 1915',
    oeuvres: 'Jean-Christophe (1904–1912) · Colas Breugnon · L\'Âme enchantée',
    intro: ['Époque : début XXe — humanisme, pacifisme, Nobel 1915.', 'Fonction : romancier engagé ; héros artiste.', 'Œuvre à citer : Jean-Christophe (1904-1912).', 'Amorce : roman fleuve et résistance de l\'artiste.', 'Phrase type : « Romain Rolland (1866-1944), écrivain pacifiste, publie Jean-Christophe de 1904 à 1912. »'],
    dev: 'Rolland célèbre la force vitale et la résistance de l\'artiste face à l\'histoire (Jean-Christophe, « vie héroïque »). Engagé pacifiste, il unit roman fleuve et idéals humanistes. Au bac : contextualise engagement, héros artiste et registre épique ou lyrique.',
  },
  {
    id: 'margueritte', nom: 'Victor Margueritte', genre: 'Roman', dates: '1866 – 1942',
    mouvement: 'Pacifisme et féminisme — société et mœurs',
    oeuvres: 'La Garçonne (1922) · Le Cavalier au masque',
    intro: ['Époque : entre-deux-guerres — féminisme, mœurs.', 'Fonction : romancier ; polémique sociale.', 'Œuvre à citer : La Garçonne (1922).', 'Amorce : émancipation féminine après 1914.', 'Phrase type : « Victor Margueritte (1866-1942), romancier, publie La Garçonne en 1922. »'],
    dev: 'Margueritte scandalise avec La Garçonne, roman qui affirme l\'émancipation féminine après 1914. Son écriture mêle réalisme social et provocation. Au bac : repère registre satirique ou polémique, portrait de la modernité des mœurs.',
  },
  {
    id: 'germain', nom: 'Sylvie Germain', genre: 'Roman', dates: '1954 –',
    mouvement: 'Contemporain — récit initiatique, mythologie et mémoire',
    oeuvres: 'Les Personnages · Jours de colère (1989) · Le Livre des nuits',
    intro: ['Époque : contemporaine — roman initiatique.', 'Fonction : romancière ; thèmes : deuil, famille, merveilleux.', 'Œuvre à citer : Jours de colère (1989).', 'Amorce : mémoire familiale et registre pathétique.', 'Phrase type : « Sylvie Germain (1954-), romancière, publie Jours de colère en 1989. »'],
    dev: 'Germain écrit des romans d\'enfance, de deuil et de résurrection, souvent ancrés dans la campagne et le merveilleux. Jours de colère mêle violence familiale et quête de sens. Au bac : analyse registre pathétique ou fantastique, temporalité du récit et symbolique.',
  },
  {
    id: 'giono', nom: 'Jean Giono', genre: 'Roman', dates: '1895 – 1970',
    mouvement: 'Écriture de la violence humaine — Provence, paix et nature',
    oeuvres: 'Le Hussard sur le toit (1951) · Regain · Un roi sans divertissement · Que ma joie demeure',
    intro: ['Époque : XXe — Provence, guerre et nature.', 'Fonction : romancier ; lyrisme et dénonciation de la violence.', 'Œuvre à citer : Le Hussard sur le toit (1951).', 'Amorce : épopée provençale face à la peur et à la guerre.', 'Phrase type : « Jean Giono (1895-1970), romancier, publie Le Hussard sur le toit en 1951. »'],
    dev: 'Giono célèbre la terre provençale tout en dénonçant la guerre et la barbarie (Le Hussard sur le toit, peste et peur). Son style est oral, lyrique et épique. Au bac : repère champs lexicaux de la nature, registre tragique ou comique, rythme de la phrase.',
  },
  {
    id: 'barbey', nom: "Jules Barbey d'Aurevilly", genre: 'Roman', dates: '1808 – 1889',
    mouvement: 'Romantisme tardif et symbolisme — diabolisme et aristocratie',
    oeuvres: 'Les Diaboliques (1874) · Une vieille maîtresse · L\'Ensorcelée',
    intro: ['Époque : second XIXe — romantisme tardif, « diabolique ».', 'Fonction : romancier ; passions criminelles, style précieux.', 'Œuvre à citer : Les Diaboliques (1874).', 'Amorce : transgression et aristocratie normande.', 'Phrase type : « Jules Barbey d\'Aurevilly (1808-1889), romancier, publie Les Diaboliques en 1874. »'],
    dev: 'Barbey cultive le récit « diabolique » : passions criminelles, aristocratie normande, style précieux et violent. Les Diaboliques sont des nouvelles choc du XIXe siècle. Au bac : analyse registre fantastique ou tragique, vocabulaire de la transgression.',
  },
  {
    id: 'duras', nom: 'Claire de Duras', genre: 'Roman', dates: '1777 – 1828',
    mouvement: 'Romantisme précoce — mémoire, colonialisme et silence',
    oeuvres: 'Ourika (1823) · Édouard · Olivier ou le Secret',
    intro: ['Époque : début XIXe — romantisme, question coloniale.', 'Fonction : romancière ; thème : altérité, exclusion.', 'Œuvre à citer : Ourika (1823).', 'Amorce : voix marginalisée et registre pathétique.', 'Phrase type : « Claire de Duras (1777-1828), romancière, publie Ourika en 1823. »'],
    dev: 'Ourika est un texte majeur sur l\'altérité et l\'exclusion : une enfant sénégalaise élevée en France découvre le racisme social. Écriture intime et registre pathétique. Au bac : focalisation, registre tragique et critique des préjugés.',
  },
  {
    id: 'gautier', nom: 'Théophile Gautier', genre: 'Roman et Poésie', dates: '1811 – 1872',
    mouvement: 'Parnasse — « art pour l\'art », perfection formelle',
    oeuvres: 'Émaux et camées · Le Capitaine Fracasse (1863) · La Comédie de la mort',
    intro: ['Époque : XIXe — Parnasse, « art pour l\'art ».', 'Fonction : poète et romancier ; recherche formelle.', 'Œuvre à citer : Émaux et camées ou Le Capitaine Fracasse (1863).', 'Amorce : beauté du vers et description picturale.', 'Phrase type : « Théophile Gautier (1811-1872), poète du Parnasse, défend l\'« art pour l\'art ». »'],
    dev: 'Gautier défend la beauté formelle indépendante du message moral (« art pour l\'art »). Poète du Parnasse et romancier du passé historique (Capitaine Fracasse). Au bac : repère descriptions picturales, sonorités et recherche esthétique du style.',
  },
  {
    id: 'prevost', nom: 'Abbé Prévost', genre: 'Roman', dates: '1697 – 1763',
    mouvement: 'Classicisme et Lumières — roman sentimental',
    oeuvres: 'Manon Lescaut (1731) · Histoire d\'une Grecque moderne',
    intro: ['Époque : XVIIIe — transition classicisme / Lumières.', 'Fonction : romancier ; roman passionnel.', 'Œuvre à citer : Manon Lescaut (1731).', 'Amorce : Baroque → classicisme (théâtre moral) puis roman des passions.', 'Phrase type : « L\'abbé Prévost (1697-1763), romancier, publie Manon Lescaut en 1731. »'],
    dev: 'Manon Lescaut fonde le roman passionnel : amour, transgression et destin tragique d\'une héroïne ambiguë. Récit en mémoire (Des Grieux). Au bac : analyse registre pathétique, narrateur et conflit passion / morale.',
  },
  {
    id: 'fenelon', nom: 'Fénelon', genre: 'Roman', dates: '1651 – 1715',
    mouvement: "Classicisme — homme d'Église, pédagogie et utopie",
    oeuvres: 'Les Aventures de Télémaque (1699) · Traité de l\'éducation des filles',
    intro: ['Époque : fin XVIIe – début XVIIIe — classicisme.', 'Fonction : archevêque, pédagogue ; épopée morale.', 'Œuvre à citer : Télémaque (1699).', 'Amorce : classicisme, visée didactique et politique.', 'Phrase type : « Fénelon (1651-1715), homme d\'Église, publie Télémaque en 1699. »'],
    dev: 'Fénelon écrit une épopée morale pour former le duc de Bourgogne : Télémaque mêle aventure, sagesse politique et idéal monarchique éclairé. Au bac : repère registre didactique, allégorie et visée pédagogique du récit.',
  },
  {
    id: 'sevigne', nom: 'Madame de Sévigné', genre: 'Roman', dates: '1626 – 1696',
    mouvement: 'Classicisme — épistolaire et salon',
    oeuvres: 'Lettres à sa fille (Mme de Grignan) · portraits du siècle de Louis XIV',
    intro: ['Époque : XVIIe — classicisme, cour de Louis XIV.', 'Fonction : épistolière ; ton intime et historique.', 'Œuvre à citer : Lettres à Mme de Grignan.', 'Amorce : classicisme, portrait du siècle et registre intime.', 'Phrase type : « Madame de Sévigné (1626-1696), épistolière du Grand Siècle. »'],
    dev: 'Madame de Sévigné est une grande épistolière : vivacité, tendresse maternelle et peinture de la cour. Les lettres sont un témoignage historique et littéraire. Au bac : analyse ton intime, registre comique ou pathétique, point de vue et époque.',
  },
  {
    id: 'bosco', nom: 'Henry Bosco', genre: 'Roman', dates: '1888 – 1976',
    mouvement: 'Hors classification — Provence, merveilleux et enfance',
    oeuvres: 'Le Mas Théotime · L\'Antiquaire · Un malentendu · Le Jardin d\'Hyacinthe',
    intro: ['Époque : XXe — Provence, merveilleux.', 'Fonction : romancier ; enfance et surnature.', 'Œuvre à citer : Le Mas Théotime ou L\'Antiquaire.', 'Amorce : récit poétique hors courants définis.', 'Phrase type : « Henry Bosco (1888-1976), romancier provençal, mêle réel et merveilleux. »'],
    dev: 'Bosco échappe aux étiquettes : récits de Provence où enfance, nature et surnature se mêlent. Style poétique et narrateur nostalgique. Au bac : repère registre fantastique ou lyrique, symbolique du lieu et du temps.',
  },
  {
    id: 'garry', nom: 'Romain Gary', genre: 'Roman', dates: '1914 – 1980',
    mouvement: 'Romantisme, réalisme et naturalisme — écriture double, engagement',
    oeuvres: 'La Promesse de l\'aube · Les Racines du ciel · Vie et mort d\'Émile Ajar',
    intro: ['Époque : XXe — engagement, double identité d\'écrivain.', 'Fonction : romancier ; épopée et autobiographie.', 'Œuvre à citer : La Promesse de l\'aube ou Les Racines du ciel.', 'Amorce : mémoire, identité et registre épique.', 'Phrase type : « Romain Gary (1914-1980), romancier, publie La Promesse de l\'aube. »'],
    dev: 'Gary mêle épopée, humour et engagement (Prix Goncourt sous deux noms). La Promesse de l\'aube est autobiographique et pathétique ; Les Racines du ciel défend la nature. Au bac : registre épique ou comique, double énonciation et thème de l\'identité.',
  },
  {
    id: 'verne', nom: 'Jules Verne', genre: 'Roman', dates: '1828 – 1905',
    mouvement: 'Réalisme scientifique — voyages extraordinaires',
    oeuvres: 'Vingt Mille Lieues sous les mers · Le Tour du monde en 80 jours · De la Terre à la Lune',
    intro: ['Époque : second XIXe — science et aventure.', 'Fonction : romancier ; « voyages extraordinaires ».', 'Œuvre à citer : Vingt Mille Lieues sous les mers (1870) ou Le Tour du monde (1873).', 'Amorce : roman d\'exploration, progrès technique.', 'Phrase type : « Jules Verne (1828-1905), romancier, publie Vingt Mille Lieues sous les mers. »'],
    dev: 'Verne popularise la science et l\'aventure : le roman devient exploration du monde et de la technique. Narration dynamique, documentation et imagination. Au bac : analyse registre descriptif, point de vue et champs lexicaux de la découverte.',
  },
  {
    id: 'giraudoux', nom: 'Jean Giraudoux', genre: 'Théâtre', dates: '1882 – 1944',
    mouvement: 'Modernité théâtrale — langage brillant, fantaisie et tragédie',
    oeuvres: "La Guerre de Troie n'aura pas lieu (1935) · Intermezzo · Électre · Ondine",
    intro: ['Époque : entre-deux-guerres — théâtre moderniste.', 'Fonction : dramaturge ; langage spirituel, mythe réécrit.', 'Œuvre à citer : La Guerre de Troie n\'aura pas lieu (1935).', 'Amorce : pacifisme et renouveau du dialogue théâtral.', 'Phrase type : « Jean Giraudoux (1882-1944), dramaturge, écrit La Guerre de Troie n\'aura pas lieu en 1935. »'],
    dev: 'Giraudoux renouvelle le théâtre par un dialogue spirituel et une réécriture mythologique (Troie = pacifisme face à la guerre). Au bac : repère registre comique et tragique, didascalies, argumentation des personnages.',
  },
  {
    id: 'quincey', nom: 'Thomas de Quincey', genre: 'Littérature d\'Idées', dates: '1785 – 1859',
    mouvement: 'Romantisme britannique — confessions, rêve et opium',
    oeuvres: 'Confessions of an English Opium-Eater · On Murder Considered as One of the Fine Arts',
    note: 'Auteur anglais, souvent étudié en version française au lycée.',
    intro: ['Époque : XIXe britannique — romantisme, autobiographie.', 'Fonction : essayiste ; rêve, opium, ville moderne.', 'Œuvre à citer : Confessions of an English Opium-Eater (1821).', 'Amorce : subjectivité romantique et prose lyrique.', 'Phrase type : « Thomas de Quincey (1785-1859), écrivain britannique, publie ses Confessions en 1821. »'],
    dev: 'Quincey invente le récit autobiographique moderne : rêves, drogue et ville (Londres) dans une prose lyrique. Au bac : analyse registre fantastique, temporalité du récit et subjectivité du narrateur.',
  },
  {
    id: 'diderot', nom: 'Denis Diderot', genre: "Littérature d'Idées", dates: '1713 – 1784',
    mouvement: 'Lumières — Encyclopédie, matérialisme et dialogue',
    oeuvres: 'Le Neveu de Rameau · Jacques le fataliste · La Religieuse · Supplément au voyage de Bougainville',
    intro: ['Époque : XVIIIe — Lumières.', 'Fonction : philosophe et écrivain ; Encyclopédie.', 'Œuvre à citer : Le Neveu de Rameau ou Jacques le fataliste.', 'Amorce : classicisme → Lumières (progrès, combat des préjugés).', 'Phrase type : « Denis Diderot (1713-1784), philosophe des Lumières, dirige l\'Encyclopédie. »'],
    dev: 'Diderot porte les Lumières : Encyclopédie, libre pensée et expérimentation romanesque (dialogues, mise en question du narrateur). Au bac : repère registre satirique ou philosophique, polyphonie et critique sociale.',
  },
  {
    id: 'boetie', nom: 'Étienne de La Boétie', genre: "Littérature d'Idées", dates: '1530 – 1563',
    mouvement: 'Renaissance humaniste — liberté et tyrannie',
    oeuvres: 'Discours de la servitude volontaire (vers 1549)',
    intro: ['Époque : XVIe — Renaissance humaniste.', 'Fonction : humaniste ; réflexion politique.', 'Œuvre à citer : Discours de la servitude volontaire.', 'Amorce : question de la liberté et du pouvoir.', 'Phrase type : « Étienne de La Boétie (1530-1563), humaniste, rédige le Discours de la servitude volontaire. »'],
    dev: 'La Boétie analyse pourquoi les peuples obéissent à un tyran : texte fondateur de la réflexion politique en français. Au bac : argumentation, antithèses et registre polémique ou philosophique.',
  },
  {
    id: 'fontenelle', nom: 'Bernard de Fontenelle', genre: "Littérature d'Idées", dates: '1657 – 1757',
    mouvement: 'Lumières précoce — popularisation scientifique',
    oeuvres: 'Entretiens sur la pluralité des mondes · Histoire des oracles',
    intro: ['Époque : fin XVIIe – XVIIIe — science et Lumières.', 'Fonction : savant et écrivain ; vulgarisation.', 'Œuvre à citer : Entretiens sur la pluralité des mondes (1686).', 'Amorce : progrès des sciences, dialogue didactique.', 'Phrase type : « Bernard de Fontenelle (1657-1757), écrivain des Lumières, publie les Entretiens sur la pluralité des mondes. »'],
    dev: 'Fontenelle vulgarise la science en prose élégante : dialogues galants entre savants et marquises. Pont entre classicisme et Lumières. Au bac : ton didactique, registre comique ou sérieux, visée pédagogique.',
  },
  {
    id: 'graffigny', nom: 'Françoise de Graffigny', genre: "Littérature d'Idées", dates: '1695 – 1758',
    mouvement: 'Lumières — regard étranger, féminisme précoce',
    oeuvres: 'Lettres d\'une Péruvienne (1747) · Cénie',
    intro: ['Époque : XVIIIe — Lumières, satire des mœurs.', 'Fonction : romancière ; regard étranger sur la France.', 'Œuvre à citer : Lettres d\'une Péruvienne (1747).', 'Amorce : critique des préjugés et forme épistolaire.', 'Phrase type : « Françoise de Graffigny (1695-1758), publie Lettres d\'une Péruvienne en 1747. »'],
    dev: 'Lettres d\'une Péruvienne : une Indienne découvre la société française — satire des mœurs et critique du statut des femmes. Forme épistolaire. Au bac : point de vue étranger, registre satirique et construction argumentée.',
  },
  {
    id: 'corneille', nom: 'Pierre Corneille', genre: 'Théâtre', dates: '1606 – 1684',
    mouvement: 'Classicisme — héros, honneur et tragédie',
    oeuvres: 'Le Cid (1637) · Horace · Cinna · Polyeucte · Rodogune',
    intro: ['Époque : XVIIe — classicisme, tragédie héroïque.', 'Fonction : dramaturge ; héros cornélien (honneur / passion).', 'Œuvre à citer : Le Cid (1637) ou Horace.', 'Amorce : Baroque → classicisme (théâtre de l\'honneur).', 'Phrase type : « Pierre Corneille (1606-1684), dramaturge, écrit Le Cid en 1637. »'],
    dev: 'Corneille invente le héros cornélien : conflit entre passion et devoir, grandeur de l\'âme. Le Cid mêle amour et honneur ; Horace oppose devoir patriotique et famille. Au bac : alexandrins, stichomythie, registre tragique et héroïque.',
  },
  {
    id: 'musset', nom: 'Alfred de Musset', genre: 'Théâtre', dates: '1810 – 1857',
    mouvement: 'Romantisme — comédie sentimentale et drame',
    oeuvres: 'Lorenzaccio · On ne badine pas avec l\'amour · Les Caprices de Marianne · Rolla',
    intro: ['Époque : XIXe — romantisme, « mal du siècle ».', 'Fonction : poète et dramaturge ; amour et désillusion.', 'Œuvre à citer : Lorenzaccio ou On ne badine pas avec l\'amour.', 'Amorce : Lumières → romantisme (subjectivité).', 'Phrase type : « Alfred de Musset (1810-1857), dramaturge romantique, écrit Lorenzaccio. »'],
    dev: 'Musset mêle légèreté comique et profondeur romantique : amour, désillusion et liberté individuelle. Lorenzaccio est un drame historique sur le pouvoir. Au bac : registre comique ou pathétique, tirades lyriques et dialogues vifs.',
  },
  {
    id: 'sarraute', nom: 'Nathalie Sarraute', genre: 'Théâtre', dates: '1900 – 1999',
    mouvement: 'Nouveau Roman — sous-conversation, psychologie du langage',
    oeuvres: 'Pour un oui ou pour un non · Le Silence · Tropismes · Martereau',
    intro: ['Époque : XXe — nouveau roman et théâtre.', 'Fonction : romancière et dramaturge ; « tropismes ».', 'Œuvre à citer : Pour un oui ou pour un non ou Tropismes.', 'Amorce : XXe, rupture avec l\'intrigue classique.', 'Phrase type : « Nathalie Sarraute (1900-1999), écrivaine, renouvelle le théâtre avec Pour un oui ou pour un non. »'],
    dev: 'Sarraute explore ce qui se joue « sous » les mots (tropismes) et renouvelle le théâtre par des conflits minuscules but violents. Au bac : analyse dialogues, sous-entendus, rupture avec l\'intrigue classique.',
  },
  {
    id: 'racine', nom: 'Jean Racine', genre: 'Théâtre', dates: '1639 – 1699',
    mouvement: "Classicisme — tragédie de la passion, unités, vers noble",
    oeuvres: 'Phèdre (1677) · Andromaque · Britannicus · Bérénice · Athalie',
    intro: ['Époque : XVIIe — classicisme, tragédie racinienne.', 'Fonction : dramaturge ; passion fatale et vers noble.', 'Œuvre à citer : Phèdre (1677) ou Andromaque.', 'Amorce : théâtre classique (unités, alexandrin).', 'Phrase type : « Jean Racine (1639-1699), dramaturge, écrit Phèdre en 1677. »'],
    dev: 'Racine concentre la tragédie sur la passion destructrice et la fatalité (Phèdre, culpabilité et désir). Style dense, psychologie et vers serrés. Au bac : registre tragique, anaphores, champs lexicaux de la passion et du devoir.',
  },
  {
    id: 'beaumarchais', nom: 'Pierre-Augustin Caron de Beaumarchais', genre: 'Théâtre', dates: '1732 – 1799',
    mouvement: 'Siècle des Lumières — comédie engagée, Figaro',
    oeuvres: 'Le Barbier de Séville (1775) · Les Noces de Figaro (1784)',
    intro: ['Époque : XVIIIe — Lumières, prélude à 1789.', 'Fonction : dramaturge ; comédie engagée, Figaro.', 'Œuvre à citer : Le Barbier de Séville (1775) ou Les Noces de Figaro (1784).', 'Amorce : théâtre des Lumières contre les privilèges.', 'Phrase type : « Beaumarchais (1732-1799), dramaturge, écrit Le Barbier de Séville en 1775. »'],
    dev: 'Beaumarchais mêle comédie populaire et critique sociale : Figaro défie les privilèges (prélude à 1789). Dialogues vifs, intrigues et registre comique. Au bac : registre satirique, didascalies et construction de la scène comique.',
  },
  {
    id: 'marivaux', nom: 'Pierre de Marivaux', genre: 'Théâtre', dates: '1688 – 1763',
    mouvement: 'Lumières — comédie de la sensibilité, « marivaudage »',
    oeuvres: 'Le Jeu de l\'amour et du hasard · Les Fausses Confidences · Le Triomphe de l\'amour',
    intro: ['Époque : XVIIIe — Lumières, comédie sentimentale.', 'Fonction : dramaturge ; jeux de l\'amour et de la parole.', 'Œuvre à citer : Le Jeu de l\'amour et du hasard.', 'Amorce : finesse psychologique (« marivaudage »).', 'Phrase type : « Pierre de Marivaux (1688-1763), dramaturge des Lumières, écrit Le Jeu de l\'amour et du hasard. »'],
    dev: 'Marivaux analyse les jeux de l\'amour et de la parole (« marivaudage » = finesse psychologique). Comédies de déguisements et de reconnaissance. Au bac : registre comique, ironie, dialogues et évolution des sentiments.',
  },
  {
    id: 'mouawad', nom: 'Wajdi Mouawad', genre: 'Théâtre', dates: '1968 –',
    mouvement: 'Contemporain — mémoire, guerre et identité',
    oeuvres: 'Incendies · Littoral · Forêts · Sang et promesses · Seuls',
    note: "Québécois, d'origine libanaise.",
    intro: ['Époque : contemporaine — théâtre québécois, guerre et exil.', 'Fonction : dramaturge ; mémoire familiale, tragédie.', 'Œuvre à citer : Incendies.', 'Amorce : XIXe → XXe (famille, absurdité, didascalies).', 'Phrase type : « Wajdi Mouawad (1968-), dramaturge québécois, écrit Incendies. »'],
    dev: 'Mouawad met en scène la violence de l\'histoire intime (guerre, exil, famille). Incendies entrelace récit, énigme et tragédie contemporaine. Au bac : didascalies, registre tragique ou poétique, structure non linéaire du récit.',
  },
  {
    id: 'voltaire', nom: 'Voltaire', genre: 'Poésie', dates: '1694 – 1778',
    mouvement: "Lumières — satire, portrait, pathos et combat de l'intolérance",
    oeuvres: 'Candide · Zadig · Micromégas · Poème sur le désastre de Lisbonne · Traité sur la tolérance',
    intro: ['Époque : XVIIIe — Lumières.', 'Fonction : philosophe, écrivain ; satire et combat des injustices.', 'Œuvre à citer : Candide (1759) ou Traité sur la tolérance (1763).', 'Amorce : classicisme → Lumières (progrès, tolérance).', 'Phrase type : « Voltaire (1694-1778), philosophe des Lumières, publie Candide en 1759. »'],
    dev: 'Voltaire utilise tous les genres pour éclairer et combattre l\'injustice : conte philosophique (Candide), satire, poème et pamphlet. Registres comique, tragique et polémique. Au bac : ironie, champs lexicaux de la critique et visée argumentative du texte.',
  },
];
